### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by KT1337**
Removed the other unnecessary path and directory in ignore list and should be ignore sites.txt file since it was a target file. it could contains the sensitive information.

### CODE REVIEW

**Comment by KT1337** [comment]
closed without merge?

**Comment by 4cc3ssX** [comment]
Sorry bro. i forgot it bcuz i'm not much know about git.

**Comment by 4cc3ssflick** [comment]
Sorry bro. i forgot it bcuz i'm not much know about git.

**Comment by 4cc3ssX** [comment]
Done bro thank u💙

**Comment by KT1337** [comment]
Now, looks cool! :)

**Pull request merged**
